name: Deploy para o Google Apps Script

on:
  push:
    branches:
      - main # ou master, dependendo da sua branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Clasp
        run: sudo npm install -g @google/clasp

      - name: Criar arquivos de configuração do Clasp
        run: |
          echo "$CLASPRC_JSON" > ~/.clasprc.json
          echo "$CLASP_JSON" > .clasp.json
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
          CLASP_JSON: ${{ secrets.CLASP_JSON }}

      - name: Enviar código para o Apps Script (clasp push)
        run: clasp push --force